name: npm publish on every push
author: Nikolay Kostyurin
description: |
  Publish to npm or the GitHub Package registry on every push, with sensible versioning conventions.

branding:
  icon: package
  color: blue

runs:
  using: docker
  image: Dockerfile
