name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          node-version: 10
          registry-url: '//registry.npmjs.org'

      - run: npm ci
      - run: npm test

      - run: bash entrypoint.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
